import time
print("Procesando...")
time.sleep(1)
print("Procesando...")
time.sleep(1)
print("Procesando...")
time.sleep(1)
print("Procesando...")
time.sleep(3)
print("Accediendo al sistema")
time.sleep(2)
print("Entrando a la base de datos")
time.sleep(2)
print("Dentro de la base de datos")
time.sleep(4)
print("Ponte a estudiar chamaco pendejo xd")
